server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user_registration
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
